<?php
/// get Wiki Article for Modal 2 (WIKIPEDIA)
// Had to manually map out the country codes as they were coming back with the wrong infromation prior
$countryMap = [
    "AF" => "Afghanistan",
    "AL" => "Albania",
    "DZ" => "Algeria",
    "AD" => "Andorra",
    "AO" => "Angola",
    "AG" => "Antigua_and_Barbuda",
    "AR" => "Argentina",
    "AM" => "Armenia",
    "AU" => "Australia",
    "AT" => "Austria",
    "AZ" => "Azerbaijan",
    "BS" => "The_Bahamas", 
    "BH" => "Bahrain",
    "BD" => "Bangladesh",
    "BB" => "Barbados",
    "BY" => "Belarus",
    "BE" => "Belgium",
    "BZ" => "Belize",
    "BJ" => "Benin",
    "BT" => "Bhutan",
    "BO" => "Bolivia",
    "BA" => "Bosnia_and_Herzegovina", 
    "BW" => "Botswana",
    "BR" => "Brazil",
    "BN" => "Brunei",
    "BG" => "Bulgaria",
    "BF" => "Burkina_Faso",
    "BI" => "Burundi",
    "CV" => "Cape_Verde", 
    "KH" => "Cambodia",
    "CM" => "Cameroon",
    "CA" => "Canada",
    "CF" => "Central_African_Republic", 
    "TD" => "Chad",
    "CL" => "Chile",
    "CN" => "China",
    "CO" => "Colombia",
    "KM" => "Comoros",
    "CG" => "Republic_of_the_Congo",
    "CD" => "Democratic_Republic_of_the_Congo", 
    "CR" => "Costa_Rica",
    "HR" => "Croatia",
    "CU" => "Cuba",
    "CY" => "Cyprus",
    "CZ" => "Czech_Republic", 
    "DK" => "Denmark",
    "DJ" => "Djibouti",
    "DM" => "Dominica",
    "DO" => "Dominican_Republic",
    "EC" => "Ecuador",
    "EG" => "Egypt",
    "SV" => "El_Salvador", 
    "GQ" => "Equatorial_Guinea", 
    "ER" => "Eritrea",
    "EE" => "Estonia",
    "SZ" => "Eswatini",
    "ET" => "Ethiopia",
    "FJ" => "Fiji",
    "FI" => "Finland",
    "FR" => "France",
    "GA" => "Gabon",
    "GM" => "The_Gambia",
    "GE" => "Georgia",
    "DE" => "Germany",
    "GH" => "Ghana",
    "GR" => "Greece",
    "GD" => "Grenada",
    "GT" => "Guatemala",
    "GN" => "Guinea",
    "GW" => "Guinea-Bissau",
    "GY" => "Guyana",
    "HT" => "Haiti",
    "HN" => "Honduras",
    "HU" => "Hungary",
    "IS" => "Iceland",
    "IN" => "India",
    "ID" => "Indonesia",
    "IR" => "Iran",
    "IQ" => "Iraq",
    "IE" => "Ireland",
    "IL" => "Israel",
    "IT" => "Italy",
    "JM" => "Jamaica",
    "JP" => "Japan",
    "JO" => "Jordan",
    "KZ" => "Kazakhstan",
    "KE" => "Kenya",
    "KI" => "Kiribati",
    "KP" => "North_Korea", 
    "KR" => "South_Korea", 
    "KW" => "Kuwait",
    "KG" => "Kyrgyzstan",
    "LA" => "Laos",
    "LV" => "Latvia",
    "LB" => "Lebanon",
    "LS" => "Lesotho",
    "LR" => "Liberia",
    "LY" => "Libya",
    "LI" => "Liechtenstein",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "MG" => "Madagascar",
    "MW" => "Malawi",
    "MY" => "Malaysia",
    "MV" => "Maldives",
    "ML" => "Mali",
    "MT" => "Malta",
    "MH" => "Marshall_Islands", 
    "MR" => "Mauritania",
    "MU" => "Mauritius",
    "MX" => "Mexico",
    "FM" => "Federated_States_of_Micronesia", 
    "MD" => "Moldova",
    "MC" => "Monaco",
    "MN" => "Mongolia",
    "ME" => "Montenegro",
    "MA" => "Morocco",
    "MZ" => "Mozambique",
    "MM" => "Myanmar",
    "NA" => "Namibia",
    "NR" => "Nauru",
    "NP" => "Nepal",
    "NL" => "Netherlands",
    "NZ" => "New_Zealand",
    "NI" => "Nicaragua",
    "NE" => "Niger",
    "NG" => "Nigeria",
    "NO" => "Norway",
    "OM" => "Oman",
    "PK" => "Pakistan",
    "PW" => "Palau",
    "PA" => "Panama",
    "PG" => "Papua_New_Guinea", 
    "PY" => "Paraguay",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PL" => "Poland",
    "PT" => "Portugal",
    "QA" => "Qatar",
    "RO" => "Romania",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "KN" => "Saint_Kitts_and_Nevis", 
    "LC" => "Saint_Lucia", 
    "VC" => "Saint_Vincent_and_the_Grenadines", 
    "WS" => "Samoa",
    "SM" => "San_Marino", 
    "ST" => "Sao_Tome_and_Principe", 
    "SA" => "Saudi_Arabia", 
    "SN" => "Senegal",
    "RS" => "Serbia",
    "SC" => "Seychelles",
    "SL" => "Sierra_Leone", 
    "SG" => "Singapore",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "SB" => "Solomon_Islands", 
    "SO" => "Somalia",
    "ZA" => "South_Africa", 
    "SS" => "South_Sudan", 
    "ES" => "Spain",
    "LK" => "Sri_Lanka",
    "SD" => "Sudan",
    "SR" => "Suriname",
    "SE" => "Sweden",
    "CH" => "Switzerland",
    "SY" => "Syria",
    "TW" => "Taiwan",
    "TJ" => "Tajikistan",
    "TZ" => "Tanzania",
    "TH" => "Thailand",
    "TL" => "Timor-Leste",
    "TG" => "Togo",
    "TO" => "Tonga",
    "TT" => "Trinidad_and_Tobago",
    "TN" => "Tunisia",
    "TR" => "Turkey",
    "TM" => "Turkmenistan",
    "TV" => "Tuvalu",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "AE" => "United_Arab_Emirates", 
    "GB" => "United_Kingdom", 
    "US" => "United_States", 
    "UY" => "Uruguay",
    "UZ" => "Uzbekistan",
    "VU" => "Vanuatu",
    "VA" => "Vatican_City", 
    "VE" => "Venezuela",
    "VN" => "Vietnam",
    "YE" => "Yemen",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe"
];
if (isset($_POST['country'])) {
    $countryCode = $_POST['country'];

    if (array_key_exists($countryCode, $countryMap)) {
        
        $countryName = $countryMap[$countryCode];
    } else {
       
        $countryName = $countryCode;
    }
    error_log("Requested country: $countryName");
    $apiUrl = 'https://en.wikipedia.org/api/rest_v1/page/summary/' . urlencode($countryName);
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $apiUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $response = curl_exec($ch);
    curl_close($ch);
    if ($response === false) {
        echo json_encode(['success' => false, 'message' => 'Failed to fetch data from Wikipedia API']);
        exit();
    }
    $wikiData = json_decode($response, true);
    if (isset($wikiData['extract']) && isset($wikiData['content_urls']['desktop']['page'])) {
        $extract = $wikiData['extract']; //article
        $wikiUrl = $wikiData['content_urls']['desktop']['page']; //link
        echo json_encode([
            'success' => true,
            'extract' => $extract,
            'url' => $wikiUrl
        ]);
    } else {
    
        echo json_encode(['success' => false, 'message' => 'No article found for the country: ' . $countryName]);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'No country provided.']);
}
?>
